"""added balance check constraint

Revision ID: 13f5936d9a1f
Revises: c191d5080536
Create Date: 2026-05-16 01:34:10.818824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f5936d9a1f'
down_revision: Union[str, Sequence[str], None] = 'c191d5080536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("ck_balance_non_negative", "wallets", "balance >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_balance_non_negative", "wallets")
    # ### end Alembic commands ###
