"""added unique constraint on wallet user_id

Revision ID: 412e794472c0
Revises: 13f5936d9a1f
Create Date: 2026-05-16 17:55:20.436015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412e794472c0'
down_revision: Union[str, Sequence[str], None] = '13f5936d9a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'wallets', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='unique')
    # ### end Alembic commands ###
